# Generated by Django 2.2.19 on 2021-10-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(db_index=True, max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('text', models.TextField(help_text='Напишите текст', verbose_name='Текст')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('upd_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
